apps/vmc/urls.py
"""Urls vmc."""
from django.urls import path

from apps.vmc import views

app_name = "vmc_sandbox"

urlpatterns = [
    path("", views.index, name="index"),
    path("app/", views.ReadList.as_view(), name="todolist"),
    path("app/items", views.item_list, name="item_list"),
    path("app/item/<int:pk>/delete", views.DeleteItem.as_view(), name="delete_item"),
    path("ajax_url_done/", views.save_done_chkbx, name="is_done"),
    path("app/item/<int:pk>/edit", views.UpdateItem.as_view(), name="update_form"),
    path("app/item/new", views.CreateItem.as_view(), name="create_form"),
    path(
        "mailbox/",
        views.ThreadList.as_view(),
        name="mailbox_thread",
    ),
    path(
        "mailbox/thread/<int:thread_id>/msg/",
        views.MessageList.as_view(),
        name="mailbox_msgs",
    ),
    path(
        "mailbox/thread/<int:thread_id>/msg/response/",
        views.msg_response,
        name="msg_response",
    ),
    path("mailbox/new/", views.create_message, name="create-msg"),
    path(
        "mailbox/thread/<int:thread_id>/msg/<int:msg_id>/",
        views.delete_message,
        name="delete-msg",
    ),
    path("mailbox/new/thread/", views.create_thread, name="create-thread"),
    path("mailbox/thread/<int:thread_id>/", views.delete_thread, name="delete_thread"),
]

apps/vmc_auth/urls.py
"""Auth urls."""
from django.urls import path
from apps.vmc_auth import views

app_name = "auth"

urlpatterns = [
    path("accounts/signup/", views.signup, name="signup"),
    # path("accounts/signin/", views.signin, name="signin"),
    path("accounts/signin/", views.LoginView.as_view(), name="signin"),
    path("accounts/signin/#signin-modal", views.signin, name="signin_modal"),
    path("accounts/profile/", views.ProfileView.as_view(), name="profile"),
    path("accounts/signout", views.user_logout, name="signout"),
    path(
        "accounts/profile/delete/<int:pk>/",
        views.DeleteAccount.as_view(),
        name="delete_account",
    ),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

app_name = "sandbox"

urlpatterns = i18n_patterns(
    path("admin/", admin.site.urls),
    path("auth/", include("apps.vmc_auth.urls")),
    path("", include("apps.vmc.urls")),
)

templates/pages/base.html
<!DOCTYPE html>
{% load i18n %}
{% load static %}
{% load extra_filters %}
<html lang="fr">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{% block title %}{% endblock title %}</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Black+Ops+One&display=swap" rel="stylesheet">
  <link rel="icon" type="image/x-icon" href="{% static 'img/favItem.png' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
    integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body id="base">
  {% csrf_token %}
  <script type="text/javascript">
    var csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
    const ajax_url_update_item = "{# url 'vmc_sandbox:get_datas_from_backend' #}"
    const ajax_url_update_modal = "{# url 'vmc_sandbox:update_modal' #}"
    const ajax_url_get_form_create = "{% url 'vmc_sandbox:create_form' %}"
    const ajax_url_save_new_item = "{# url 'vmc_sandbox:save_item' #}"
    const ajax_url_index = "{% url 'vmc_sandbox:todolist' %}"
    const ajax_url_done = "{% url 'vmc_sandbox:is_done' %}"
    const ajax_url_post_signin = "{% url 'auth:signin' %}"
    const ajax_url_post_signup = "{% url 'auth:signup' %}"
  </script>
  {% spaceless %}
<nav class="navbar navbar-expand-lg navbar-bg mb-5 z-2">
  <div class="container-fluid">
    <button class="navbar-toggler me-3" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'vmc_sandbox:index' %}"><span class="applogo">BacASand</span>
      <p class="lh-applogo">{% translate slogan %}</p>
    </a>
    <button id="ligbtn" data-light="light" class="light-button btn ms-auto me-0 order-lg-last"
    hidden>
    <i class="fa-solid fa-sun fa-xl"></i>
    </button>
    <button id="darkbtn" data-dark="dark" class="dark-button btn ms-auto me-0 order-lg-last">
      <i class="fa-solid fa-moon fa-xl"></i>
    </button>
    <div class="collapse navbar-collapse d-lg-flex" id="navbarSupportedContent">
        {% if user.is_authenticated %}
          <ul class="navbar-nav col-lg-6 justify-content-lg-start">
            <li class="nav-item dropdown">
              <a class="dropdown-toggle btn btn-secondary" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {% translate myaccount %} ({{user.username}})
              </a>
              <ul class="dropdown-menu mb-2">
                <li><a class="dropdown-item" href="{% url 'vmc_sandbox:todolist' %}">App</a></li>
                <li><a class="dropdown-item" href="{% url 'auth:profile' %}">{% translate profile %}</a></li>
                {% if user.is_staff %}
                <li><a class="dropdown-item" href="{% url 'vmc_sandbox:mailbox_thread' %}">{% translate mailbox %}</a></li>
                {% endif %}
                <li><a class="dropdown-item" href="{% url 'auth:signout' %}">{% translate logout %}</a></li>
              </ul>
            </li>
          </ul>
          <div class="d-lg-flex col-lg-5 justify-content-lg-end">
        {% else %}
            <ul class="list-group list-group-horizontal-lg ms-auto">    
              <li class="btn btn-secondary m-2">    
                <a class="nav-link text-light" href="#" data-bs-toggle="modal" data-bs-target="#signup-modal" aria-current="page"
                data-url-signup="{% url 'auth:signup' %}" data-signup>{% translate signup %}
              </a>
            </li>
            <li class="btn btn-secondary m-2">
              <a class="nav-link text-light" href="#" data-bs-toggle="modal" data-bs-target="#mosi"
                data-url="{% url 'auth:signin' %}" data-url-next="{% url 'auth:signin' %}?next=/app/" data-signin>{% translate login %}
              </a> 
            </li>
          </ul>   
        {% endif %}
      </div>
    </div>
  </div>
</nav>

<div id="lang-selector" class="position-absolute lang-top end-0 me-3 btn btn-sm btn-secondary">Language: {{ request.path|get_current_url_lang|capfirst }}</div>
<div id="languages" class="position-absolute lang-top lang-right " hidden>
    <span class="lang me-2 btn btn-sm btn-secondary" id="fr">Français</span>
    <span class="lang me-2 btn btn-sm btn-secondary" id="en">English</span>
</div>

  {% endspaceless %}
  {% if messages %}
    {% for message in messages %}
      <div class="m-4 alert {% if message.tags %}alert-{{ message.tags }}{% endif %}" role="alert">{{ message }}</div>
    {% endfor %}
  {% endif %}
  {% block item_list %}{% endblock item_list %}
  {% block home %}{% endblock home %}
  {% block mailbox %}{% endblock mailbox %}
  {% block create_msg %}{% endblock create_msg %}
  {% block create_thread %}{% endblock create_thread %}
  {% block content %}{% endblock content %}
  {% block signin_modal %}{% endblock signin_modal %}
  {% block update_item %}{% endblock update_item %}
  {% block profile %}{% endblock profile %}
  {% block add_item %}{% endblock add_item %}
  {% block delete_item %}{% endblock delete_item %}
  {% block signup %}{% endblock signup %}
  {% block signin %}{% endblock signin %}
  {% block upd_form %}{% endblock upd_form %}
  {% block user_confirm_delete %}{% endblock user_confirm_delete %}
  {% include 'pages/modal_signin.html' %}
  {% include 'pages/modal_signup.html' %}
  <script src="{% static 'js/get_form_signup.js' %}"></script>
  <script src="{% static 'js/get_form_signin.js' %}"></script>
  <script src="{% static 'js/post_form_signin.js' %}"></script>
  <script src="{% static 'js/post_form_signup.js' %}"></script>


  <script>
    const langSelector = document.getElementById("lang-selector")
    const divLang = document.getElementById("languages")
    const span = document.getElementsByClassName("lang")

    langSelector.onclick = (event) => {
        if (event.target.id === "lang-selector" && langSelector.classList.contains("clicked")) {
            langSelector.classList.remove("clicked");
            divLang.setAttribute("hidden", "");
        } else {
            langSelector.classList.add("clicked");
            divLang.removeAttribute("hidden", "");
            span["en"].onclick = (e) => {
                window.location.href = `/${span["en"].id}/` + "{{ request.path|complete_current_url_lang }}";
                event.target.innerHTML = "{{ request.path|get_current_url_lang|capfirst }}"
            }
            span["fr"].onclick = (e) => {
                window.location.href = `/${span["fr"].id}/` + "{{ request.path|complete_current_url_lang }}";
                event.target.innerHTML = "{{ request.path|get_current_url_lang|capfirst }}"
            }
        }
    }
</script>

  {% if not user.is_authenticated %}
    <script>
      let signModals = ["mosi", "signup-modal"]
      signModals.forEach(modal => {
        var signMod = new bootstrap.Modal(document.getElementById(modal))
        document.addEventListener('keydown', (event) => {
          if (event.key === 'Escape') {
            signMod.hide()
          }

          if (event.key === 'Enter') {
            event.preventDefault();
          }
        })
      });

      async function getJsonDataSignin(url, headers) {
        try {
          const response = await fetch(url, {
            method: 'GET',
            headers: headers
          })
          return await response.text()
        } catch (err) {
          return console.warn(err)
        }
      }
      document.addEventListener("DOMContentLoaded", function () {
        if (window.location.href.indexOf("#mosi") > -1) {
          let signinModal = new bootstrap.Modal(document.getElementById('mosi'));
          getJsonDataSignin(
            "/auth/accounts/signin",
            { "X-CSRFToken": csrftoken }
          ).then((response) => {
            sif.innerHTML = response
          })
          signinModal.show();
        }
      });
    </script>
    {% endif %}
    <script src="{% static 'js/toggle_mode_propa.js' %}"></script>
    {% if not user.is_authenticated %}
    <noscript>
      <a href="{% url 'auth:signin' %}">Se connecter</a>
    </noscript>
  {% endif %}
</body>
</html>

templates/pages/create_form.html
{% csrf_token %}

{{ form.title.errors }}
{{ form.title.label_tag }}
{{ form.title }}
{{ form.task.errors }}
{{ form.task.label_tag }}
{{ form.task }}
{{ form.date.errors }}
{{ form.date.label_tag }}
{{ form.date }}

templates/pages/delete_object.html
    {% csrf_token %}
    <p class="text-bg-light p-3">
        <b>{{ object.title }}</b>
        <br>détail :{{ object.task }}
        <br>du {{ object.date|date:"d m Y" }}
    </p>

templates/pages/index.html
{% extends 'pages/base.html' %}
{% load static %}
{% load i18n %}

{% block title %}BacaSand{% endblock %}
{% block home %}
<main class="container">

        {{msg}}

    <div id="bas" class="bg-light p-5 rounded">


        <p><span class="applogo">BacaSand</span> {% translate pres1 %}</p>

        <p>{% translate pres2 %}</p>
        <div class="gal">
            <ul>
                <li><img src="https://www.python.org/static/community_logos/python-logo-master-v3-TM.png" alt="python"
                        width="150PX" class="m-2 float-start"></li>
                <li><img src="https://www.djangoproject.com/m/img/logos/django-logo-negative.svg" alt="django"
                        width="150PX" class="m-2 float-start"></li>
                <li><img src="https://upload.wikimedia.org/wikipedia/commons/c/c5/Nginx_logo.svg" alt="nginx"
                        width="150PX" class="m-2 float-start"></li>
                <li><img src="https://upload.wikimedia.org/wikipedia/commons/0/00/Gunicorn_logo_2010.svg" alt="gunicorn"
                        width="150PX" class="m-2 float-start"></li>
                <li><img src="https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png" alt="javascript"
                        width="75px" height="75px" class="m-2 float-start"></li>
                <li><img src="https://upload.wikimedia.org/wikipedia/fr/b/b3/Jquery-logo.png" alt="jquery" width="150PX"
                        class="m-2 float-start"></li>
            </ul>
        </div>
        <p>{% translate pres3 %}</p>
    </div>






    </div>



</main>
{% endblock home %}

templates/pages/list.html
{% load i18n %}
{% for item in item_list %}
    {% if user.id == item.user_id %}
        <tr>
            <td>
                {% if item.is_done %}
                    <label class="btn fa fa-check-circle fa-2x text-success pe-2 pb-2 pt-2" id="{{item.pk}}" for="btncheck-{{item.pk}}" aria-hidden="true"></label>
                    <input name="is-done" data-ckbx type="checkbox" class="btn-check" id="btncheck-{{item.pk}}" value="{{item.pk}}" autocomplete="off" checked>    
                {% else %}
                    <label class="btn fa fa-flag fa-2x text-secondary pe-2 pb-2 pt-2" id="{{item.pk}}" for="btncheck-{{item.pk}}"></label>
                    <input name="is-done" data-ckbx type="checkbox" class="btn-check" id="btncheck-{{item.pk}}" value="{{item.pk}}" autocomplete="off">
                {% endif %}
            </td>
            
            <td>{{item.title}}</td>
            <td>{{item.task}}</td>
            <td>{{item.date|date:'d-m-Y'}}</td>
            <td>
                <button id="edit" name="live-edit" data-bs-toggle="modal" data-btn-edit
                    data-item-id="{{item.pk}}" data-bs-target="#update_modal"
                    data-url="{% url 'vmc_sandbox:update_form' item.pk %}"
                    class="btn btn-primary live-edit btn-size fas fa-pen pe-2 pb-2 pt-2">
                </button>
            </td>
            <td>
                <button class="btn btn-warning btn-size fas fa-trash-alt pe-2 pb-2 pt-2" data-bs-toggle="modal" data-bs-target="#delete_modal" data-btn-delete data-item-id="{{item.pk}}"
                    id="del" data-btn-del>
                </button>
            </td>
        </tr>
    {% endif %}
{% endfor %}

templates/pages/mailbox.html
{% extends 'pages/base.html' %}
{% load i18n %}
{% load static %}
{% load extra_filters %}
{% block title %}Mailbox{% endblock %}
{% block mailbox %}

{% include 'pages/update_item.html' %}
{% include 'pages/modal_create.html' %}
{% include 'pages/delete_item.html' %}

<main class="container" id="read-container">
    <div class="bg-dark-subtle p-5 rounded">
        {% if user.is_staff %}
            {% if thread_id %}
                <h1>Discussion : {{thread.title}}</h1><hr>
            {% else %}
                <h1>Mailbox</h1><hr>
            {% endif %}
            
            {% if "/fr/mailbox/" == request.path or "/en/mailbox/" == request.path %}
            <h2><a class="btn btn-info mt-5" href="{% url 'vmc_sandbox:create-thread'  %}" >Créer une discussion</a></h2>
            {% else %}
            <a href="{% url 'vmc_sandbox:mailbox_thread' %}" class="inbox-icon">Retour Mailbox</a>
            {% endif %}

            {% for thread in thread_list %}
                <table id="table" class="table table-striped mt-5">
                    <colgroup>
                        <col span="1" style="width: 10%" />
                        <col span="1" style="width: 20%" />
                        <col span="1" style="width: 50%" />
                        <col span="1" style="width: 15%" />
                        <col span="1" style="width: 5%" />
                    </colgroup>
                    <thead>
                        <tr>
                        </tr>
                        <tr>
                            <th>Émetteur</th>
                            <th>Destinataire(s)</th>
                            <th>Discussion</th>
                            <th>Nb de reponse</th>
                            <th>Suppr</th>
                        </tr>
                    </thead>
                    <tbody id="tbl-create">
                        {% include 'pages/list.html' %}
                        <tr>
                            <td>{{thread.sender|capfirst}}</td>
                            <td>{{thread.receiver.all|join:", "|title}}</td>
                            <td><a class="link-secondary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover" href="{% url 'vmc_sandbox:mailbox_msgs' thread.id %}">{{thread.title}}</a></td>
                            <td>{{all_msg|count_msg_by_thread:thread.id}} msg</td>
                            <td><a class="fas fa-trash-alt pe-2 pb-2 pt-2" href="{% url 'vmc_sandbox:delete_thread' thread.id %}"></a></td>
                        </tr>
                    </tbody>
                    
                </table>
            {% endfor %}
            {% include 'pages/maibox_list.html' %}
        {% else %}Cette page n'existe pas{% endif %}
    </div>
</main>

{% endblock mailbox %}

templates/pages/message_form.html
{% extends 'pages/base.html' %}
{% load static %}
{% block create_msg %}

<main class="container" id="read-container">
  <div class="bg-dark-subtle p-5 rounded">
    {% if thread_id %}
    <h1>Envoyer une réponse</h1><hr>
{% else %}
<h1>Envoyer un message</h1><hr>
  {% endif %}
  <div class="form-group">
    <form method="post">

      {% csrf_token %} 
      {{form}}
      
      <input type="submit" value="Valider" class="btn btn-primary mt-3 me-2 ms-2 float-end" />
      <a href="
      {% if thread_id %}
      {% url 'vmc_sandbox:mailbox_msgs' thread_id %}
      {% else %}
      {% url 'vmc_sandbox:mailbox_thread' %}
      {% endif %}
       " class="btn btn-warning mt-3 float-end">Annuler</a>

    </form>
  </div>
</div>
</main>
{% endblock create_msg %}

templates/pages/modal_create.html
{% block create_modal %}
{% load i18n %}
{% spaceless %}
<div class="container mt-3" id="modal-container">
    <!-- Version create bs-modal -->
    <div class="modal" id="create_modal">
        <div class="modal-dialog">
            <div class="modal-content modal-bg">
                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title text-light">{% translate modal_create_title %}</h4>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>
                <!-- Modal body -->
                <div class="col-12 p-3 bg-light">
                    <form method="post">
                        <div id="cf">
                            {% include 'pages/create_form.html' %}
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary mr-1" data-bs-dismiss="modal">{% translate cancel %}</button>
                    <button type="button" href="{% url 'vmc_sandbox:index' %}" class="btn btn-primary m-0"
                         id="validator" data-validate>{% translate submit %}</button>
                </div>

            </div>
        </div>
    </div>
</div>
{% endspaceless %}
{% endblock create_modal %}

templates/pages/modal_signin.html
{% block signin_modal %}
{% spaceless %}
<div class="container mt-3" id="modal-container">
    <!-- Version signin bs-modal -->
    <div class="modal" id="mosi">
        <div class="modal-dialog">
            <div class="modal-content modal-bg">
                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title text-light">Log in</h4>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>
                <!-- Modal body -->
                <div class="col-12 p-3 bg-light">
                    <form method="post">{% csrf_token %}
                        <div id="sif">
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-primary" value="sign-in" id="signin-btn">Se connecter</button>
                    <input type="hidden" name="next" value="{{ next }}" />
                </div>

            </div>
        </div>
    </div>
</div>
{% endspaceless %}
{% endblock signin_modal %}

templates/pages/navbar.html
{% extends 'pages/base.html' %}


{% block navbar %}
{% spaceless %}
<nav class="navbar navbar-expand-lg navbar-bg mb-5">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><span class="applogo">BacASand</span>
      <p class="lh-applogo">{% translate slogan %}</p>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse d-lg-flex" id="navbarSupportedContent">
      {% if user.is_authenticated %}
        <ul class="navbar-nav col-lg-9 justify-content-lg-middle">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Mon compte ({{user.username}})
            </a>
            <ul class="dropdown-menu mb-2">
              <li><a class="dropdown-item" href="{% url 'vmc_sandbox:todolist' %}">App</a></li>
              <li><a class="dropdown-item" href="{% url 'auth:profile' %}">Profil</a></li>
              {% if user.is_staff %}
              <li><a class="dropdown-item" href="{% url 'vmc_sandbox:mailbox_thread' %}">Mailbox</a></li>
              {% endif %}
              <li><a class="dropdown-item" href="{% url 'auth:signout' %}">Log out</a></li>
            </ul>
          </li>
        </ul>
        <div class="d-lg-flex col-lg-3 justify-content-lg-end mb-2">
          <button id="ligbtn" data-light="light" class="light-button btn btn-dark w-100px" hidden>Light&nbsp;&nbsp;
            <i class="fa-solid fa-sun"></i>
          </button>
          <button id="darkbtn" data-dark="dark" class="dark-button btn btn-dark w-100px">Dark&nbsp;&nbsp;
            <i class="fa-solid fa-moon"></i>
          </button>
        </div>
      {% else %}
        <div class="navbar-nav col-lg-12 justify-content-lg-end">
          <div class="d-lg-flex col-lg-3 justify-content-lg-end mb-2">
            <button id="ligbtn" data-light="light" class="light-button btn btn-dark w-100px me-2"
              hidden>Light&nbsp;&nbsp;
              <i class="fa-solid fa-sun"></i>
            </button>
            <button id="darkbtn" data-dark="dark" class="dark-button btn btn-dark w-100px me-2">Dark&nbsp;&nbsp;
              <i class="fa-solid fa-moon"></i>
            </button>
          </div>
          <div class="d-lg-flex justify-content-lg-end mb-2 me-2">
            <button type="button" class="btn btn-danger">
              <a class="text-light" href="#" data-bs-toggle="modal" data-bs-target="#signup-modal" aria-current="page"
                data-url-signup="{% url 'auth:signup' %}" data-signup>Sign up
              </a>
            </button>
          </div>
          <div class="d-lg-flex justify-content-lg-end mb-2">
            <button type="button" class="btn btn-info">
              <a class="text-light" href="#" data-bs-toggle="modal" data-bs-target="#mosi"
                data-url="{% url 'auth:signin' %}" data-url-next="{% url 'auth:signin' %}?next=/app/" data-signin>Log in
              </a>
            </button>
          </div>
        </div>
      {% endif %}
    </div>
  </div>
</nav>
{% endspaceless %}
{% endblock navbar %}

templates/pages/signup_form.html
{{form}}

templates/pages/thread.html
{% extends 'pages/base.html' %}
{% load static %}
{% block create_thread %}

<main class="container" id="read-container">
    <div class="bg-dark-subtle p-5 rounded">
  <h1>Créer une discussion</h1><hr>
  <div class="form-group">
    <form method="post">

      {% csrf_token %} {{form}}
      <input type="submit" value="Valider" class="btn btn-primary mt-3 me-2 ms-2 float-end" />
      <a href="{% url 'vmc_sandbox:mailbox_thread' %}"
        class="btn btn-warning mt-3 float-end">Annuler</a>

    </form>
  </div>
</div>
</main>
{% endblock create_thread %}

templates/pages/update_form.html
{% block upd_form %}
    {{ form.title.errors }}
    {{ form.title.label_tag }}
    {{ form.title }}
    {{ form.task.errors }}
    {{ form.task.label_tag }}
    {{ form.task }}
    {{ form.date.errors }}
    {{ form.date.label_tag }}
    {{ form.date }}
{% endblock upd_form %}

templates/pages/update_item.html
{% block update_item %}
{% load i18n %}
{% spaceless %}
<div class="container mt-3">
    <div class="modal" id="update_modal">
        <div class="modal-dialog">
            <div class="modal-content modal-bg">
                <form method="post" id="post_upd">{% csrf_token %}
                    <div class="modal-header">
                        <h4 class="modal-title text-light">{% translate modal_update_title %}</h4>
                        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                    </div>
                    <div class="col-12 p-3 bg-light">
                        <div id="muf">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button id="close" type="button" class="btn btn-secondary" data-bs-dismiss="modal">{% translate cancel %}</button>
                        <button type="button" class="btn btn-primary"
                            id="btn-update" data-valid-update>{% translate submit %}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endspaceless %}
{% endblock update_item %}